name: test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:


##Test the sampler
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install CI
        run: npm ci

      - name: Run tests
        run: npm test

##test the transformer 
  transformer: 
    name: Test the Transformer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pytest
        run: pip install flask pytest requests

      - name: Run Transformer tests via pytest
        run: pytest test/test_transformer.py -v

##test the REST API 
  restapi:
    name: Test the REST API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install flask pytest psycopg2-binary

      - name: Run REST API tests
        run: pytest test/test_rest_api.py -v

##tets the pipeline
  pipeline: 
    name: test the Pipeline 
    runs-on: ubuntu-latest
    needs: [test, transformer, restapi]
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4 
      
      - name: Make the Docker Image
        run: docker compose build
      
      - name: Start Database and Rest API 
        run: docker compose up -d db restapi
      
      - name: wait for Database to be up 
        run: sleep 10

      - name: test store and grabbing temperature readings
        run: |
          curl -X POST http://localhost:6000/temperature \
            -H "Content-Type: application/json" \
            -d '{"temperature": 22.5, "timestamp": "2026-01-01T12:00:00Z"}'
          
          curl http://localhost:6000/records | grep "22.5"  